# Generated by Django 3.2.25 on 2024-12-23 11:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poin', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'superadmin'), (2, 'admin'), (3, 'user')], default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('nama_booking', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('waktu_booking', models.DateField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id_content', models.AutoField(primary_key=True, serialize=False)),
                ('nama_konten', models.CharField(max_length=100)),
                ('deskripsi_konten', models.TextField()),
                ('experience', models.TextField()),
                ('gambar', models.TextField()),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id_currency', models.AutoField(primary_key=True, serialize=False)),
                ('negara_input', models.CharField(max_length=100)),
                ('negara_tujuan', models.CharField(max_length=100)),
                ('nilai_konversi', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100)),
                ('deskripsi_kategori', models.TextField()),
                ('icon_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
                ('komentar', models.TextField()),
                ('tanggal_review', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_transaksi', models.CharField(max_length=100)),
                ('status_transaksi', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 12, 23, 11, 20, 26, 212673, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 12, 23, 11, 20, 26, 212673, tzinfo=utc))),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tourism.booking')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tourism.content')),
            ],
        ),
        migrations.CreateModel(
            name='SubKategori',
            fields=[
                ('id_subkategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_subkategori', models.CharField(max_length=100)),
                ('deskripsi_subkategori', models.TextField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='tourism.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id_promo', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('gambar', models.TextField()),
                ('expiry_date', models.DateField()),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='tourism.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tourism.review'),
        ),
        migrations.AddField(
            model_name='content',
            name='subkategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tourism.subkategori'),
        ),
        migrations.AddField(
            model_name='booking',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tourism.content'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('gambar', models.TextField()),
                ('konten', models.TextField()),
                ('tanggal_post', models.DateTimeField(default=datetime.datetime(2024, 12, 23, 11, 20, 26, 216181, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
